:- assertz(spec_plan_refinement_kb:kb_status(t01, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t02, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t03, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t04, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t05, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t06, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t07, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t08, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t09, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t10, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t11, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t12, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t13, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t14, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t15, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t16, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t17, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t18, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t19, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t20, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t21, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t22, done)).
:- assertz(spec_plan_refinement_kb:kb_status(t23, done)).
