(defpackage #:prolog-rlm
  (:use #:cl)
  (:export
   #:connection
   #:start-rlm
   #:stop-rlm
   #:with-rlm
   #:call-prolog
   #:call-rlm
   #:module-exports
   #:response-ok-p
   #:binding-term
   #:prolog-term
   #:prolog-term-text
   #:raw-term
   #:prolog-var
   #:var
   #:pdict
   #:tagged-dict
   #:pcompound
   #:make-tool-schema
   #:create-tool-registry
   #:destroy-tool-registry
   #:register-symbolic-tool
   #:invoke-tool
   #:sym-field
   #:sym-path
   #:sym-const
   #:sym-and
   #:sym-or
   #:sym-not
   #:sym=
   #:sym/=
   #:sym<
   #:sym<=
   #:sym>
   #:sym>=
   #:sym-in
   #:sym-present
   #:sym-add
   #:sym-sub
   #:sym-mul
   #:sym-div
   #:sym-min
   #:sym-max
   #:sym-expr
   #:sym-rule
   #:sym-program))
